### ISSUE TITLE
Brunch Build Error for compiler.type

### ISSUE THREAD

**Issue by drewzboto** [nezoomie/brunch-eggs-and-bacon#4]
This is after working around the issue in https://github.com/nezoomie/brunch-eggs-and-bacon/issues/2, for a newly created project:

node -v
v0.6.19

brunch -v
1.2.2

Mac OSX 10.7.3

12 Jun 23:27:17 - debug: Initializing fs_utils.SourceFile: { path: 'app/models/collection.js',
  isHelper: false,
  isVendor: false }

/usr/local/lib/node_modules/brunch/lib/fs_utils/source_file.js:26
      this.type = this.compiler.type;
                               ^
TypeError: Cannot read property 'type' of undefined
    at new SourceFile (/usr/local/lib/node_modules/brunch/lib/fs_utils/source_file.js:26:32)
    at FileList._add (/usr/local/lib/node_modules/brunch/lib/fs_utils/file_list.js:132:14)
    at FileList.<anonymous> (/usr/local/lib/node_modules/brunch/lib/fs_utils/file_list.js:152:78)
    at FileList._change (/usr/local/lib/node_modules/brunch/lib/fs_utils/file_list.js:4:61)
    at FileList.emit (events.js:77:17)
    at BrunchWatcher.<anonymous> (/usr/local/lib/node_modules/brunch/lib/commands/watch.js:106:28)
    at BrunchWatcher.changeFileList (/usr/local/lib/node_modules/brunch/lib/commands/watch.js:4:61)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/brunch/lib/commands/watch.js:126:24)
    at EventEmitter.emit (events.js:67:17)
    at EventEmitter._handleFile (/usr/local/lib/node_modules/brunch/node_modules/chokidar/lib/index.js:98:8)

**Comment by paulmillr** [comment]
this is a brunch error. It's fixed in latest unstable release which will be released on this week.

**Comment by drewzboto** [comment]
awesome thanks. just pulled master and it works
